### PR TITLE
Featured Products (WIP)

### PR DESCRIPTION
**Pull request by joshierin**
- Edited description
- Added pictures
- Create classes
- Fixed structure

### CODE REVIEW

**Comment by jjpormento21** [comment]
Deleted env because it shouldn't be in the source control in the first place. Will send instructions on how to initialize the venv in your machine.

**Comment by joshierin** [comment]
- Edited catalog
- Added description
- Fixed lay-out

**Comment by jjpormento21** [comment]
Homepage and catalog improved. Added tooltips and enhanced the category section. Also added some functionality in the buttons

**Comment by jjpormento21** [comment]
This pull request has been merged with the following:
- About Us
- Product Catalog

**Pull request merged**
